/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface Page01 {
    }
    interface WcComponent02 {
        "lastname": string;
        "name": string;
    }
    interface WcComponents {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPage01Element extends Components.Page01, HTMLStencilElement {
    }
    var HTMLPage01Element: {
        prototype: HTMLPage01Element;
        new (): HTMLPage01Element;
    };
    interface HTMLWcComponent02Element extends Components.WcComponent02, HTMLStencilElement {
    }
    var HTMLWcComponent02Element: {
        prototype: HTMLWcComponent02Element;
        new (): HTMLWcComponent02Element;
    };
    interface HTMLWcComponentsElement extends Components.WcComponents, HTMLStencilElement {
    }
    var HTMLWcComponentsElement: {
        prototype: HTMLWcComponentsElement;
        new (): HTMLWcComponentsElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "page-01": HTMLPage01Element;
        "wc-component02": HTMLWcComponent02Element;
        "wc-components": HTMLWcComponentsElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface Page01 {
    }
    interface WcComponent02 {
        "lastname"?: string;
        "name"?: string;
    }
    interface WcComponents {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "page-01": Page01;
        "wc-component02": WcComponent02;
        "wc-components": WcComponents;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "page-01": LocalJSX.Page01 & JSXBase.HTMLAttributes<HTMLPage01Element>;
            "wc-component02": LocalJSX.WcComponent02 & JSXBase.HTMLAttributes<HTMLWcComponent02Element>;
            "wc-components": LocalJSX.WcComponents & JSXBase.HTMLAttributes<HTMLWcComponentsElement>;
        }
    }
}
